CODE_OF_CONDUCT.md
CONTRIBUTING.md
DCO
OWNERS.md
README.md
STYLE.md

docs: Added initial contribution docs

---

CONTRIBUTING.md

Signed-off-by: Rama <rama.rao@salesforce.com>

added commit guidelines

---

pom.xml

Signed-off-by: Sean Sullivan <ssullivan@gilt.com>

lib: grpc 1.9.0 -> grpc 1.10.0

---

.circleci/config.yml
pom.xml

We need an ssh key with read/write access from CircleCI before this will actually work.

build: Added CircleCI-based release process

---

.circleci/config.yml
api/pom.xml

build: Skip checkstyle for api module and update CI user

---

.circleci/config.yml
.circleci/settings.xml
pom.xml

build: Added code signing

---

.circleci/config.yml

build: Prevent re-deploy during release process

---

.circleci/config.yml

build: Fix git commit message capture

---

.circleci/config.yml

build: Do not release:perform, deploy happens on release commit

---

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java

Fixes https://github.com/envoyproxy/java-control-plane/issues/15
Signed-off-by: Rama <rama.rao@salesforce.com>

server: make responseObserver synchronized

---

api/src/main/proto/envoy/api/v2/cds.proto
api/src/main/proto/envoy/api/v2/discovery.proto
api/src/main/proto/envoy/api/v2/eds.proto
api/src/main/proto/envoy/api/v2/endpoint/load_report.proto
api/src/main/proto/envoy/api/v2/lds.proto
api/src/main/proto/envoy/api/v2/rds.proto
api/src/main/proto/envoy/api/v2/route/route.proto
api/src/main/proto/envoy/config/filter/accesslog/v2/accesslog.proto
api/src/main/proto/envoy/config/filter/http/ip_tagging/v2/ip_tagging.proto
api/src/main/proto/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
api/src/main/proto/envoy/service/accesslog/v2/als.proto
api/src/main/proto/envoy/service/auth/v2/external_auth.proto
api/src/main/proto/envoy/service/discovery/v2/ads.proto
api/src/main/proto/envoy/service/discovery/v2/hds.proto
api/src/main/proto/envoy/service/load_stats/v2/lrs.proto
api/src/main/proto/envoy/service/metrics/v2/metrics_service.proto
api/src/main/proto/envoy/service/trace/v2/trace_service.proto
api/src/main/proto/envoy/type/range.proto
tools/API_SHAS

This brings in https://github.com/envoyproxy/data-plane-api/commit/1dcdaaaf0853c5258aa9d1588a052ca51dbbfa7d and other updates

api: Update to latest version of data-plane-api

---

api/src/main/proto/envoy/admin/v2/config_dump.proto
api/src/main/proto/envoy/api/v2/cds.proto
api/src/main/proto/envoy/api/v2/core/address.proto
api/src/main/proto/envoy/api/v2/core/base.proto
api/src/main/proto/envoy/api/v2/core/health_check.proto
api/src/main/proto/envoy/api/v2/core/http_uri.proto
api/src/main/proto/envoy/api/v2/core/protocol.proto
api/src/main/proto/envoy/api/v2/endpoint/endpoint.proto
api/src/main/proto/envoy/api/v2/lds.proto
api/src/main/proto/envoy/api/v2/route/route.proto
api/src/main/proto/envoy/config/filter/accesslog/v2/accesslog.proto
api/src/main/proto/envoy/config/filter/fault/v2/fault.proto
api/src/main/proto/envoy/config/filter/http/health_check/v2/health_check.proto
api/src/main/proto/envoy/config/filter/http/ip_tagging/v2/ip_tagging.proto
api/src/main/proto/envoy/config/filter/http/jwt_authn/v2alpha/config.proto
api/src/main/proto/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
api/src/main/proto/envoy/config/filter/network/tcp_proxy/v2/tcp_proxy.proto
api/src/main/proto/envoy/config/metrics/v2/stats.proto
api/src/main/proto/envoy/type/percent.proto
api/src/main/proto/envoy/type/range.proto
tools/API_SHAS

api: Update data-plane-api to d0d3a05

---

cache/src/main/java/io/envoyproxy/controlplane/cache/Snapshot.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SnapshotTest.java

cache: Added Snapshot#create overload with separate versions per type

---

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
cache/src/main/java/io/envoyproxy/controlplane/cache/Watch.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java
cache/src/test/java/io/envoyproxy/controlplane/cache/WatchTest.java

cache: Don't expose reactor implementation details

---

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServerCallbacks.java
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java

server: Added discovery server callbacks

---

.circleci/config.yml
.gitignore
buildscripts/checkstyle.xml
cache/src/main/java/io/envoyproxy/controlplane/cache/TestResources.java
pom.xml
server/pom.xml
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerAdsIT.java
server/src/test/java/io/envoyproxy/controlplane/server/EchoContainer.java
server/src/test/java/io/envoyproxy/controlplane/server/EnvoyContainer.java
server/src/test/java/io/envoyproxy/controlplane/server/NettyGrpcServerRule.java
server/src/test/java/io/envoyproxy/controlplane/server/TestSnapshots.java
server/src/test/resources/docker/host_ip.sh
server/src/test/resources/envoy/ads.config.yaml
server/src/test/resources/envoy/launch_envoy.sh

test: Initial ADS integration test

---

.circleci/config.yml

build: Remove gpg --pinentry-mode flag to support gpg 2.0

---

pom.xml

build: Remove maven gpg --pinentry-mode flag to support gpg 2.0

---

pom.xml

build: Fix jacoco data file path

---

cache/src/main/java/io/envoyproxy/controlplane/cache/TestResources.java
cache/src/test/java/io/envoyproxy/controlplane/cache/ResourcesTest.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SnapshotTest.java
pom.xml
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerXdsIT.java
server/src/test/java/io/envoyproxy/controlplane/server/TestSnapshots.java
server/src/test/resources/envoy/xds.config.yaml
test/pom.xml

test: XDS integration test

---

cache/src/main/java/io/envoyproxy/controlplane/cache/ConfigWatcher.java
cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
cache/src/main/java/io/envoyproxy/controlplane/cache/Watch.java
cache/src/test/java/io/envoyproxy/controlplane/cache/CacheStatusInfoTest.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java
cache/src/test/java/io/envoyproxy/controlplane/cache/WatchTest.java
server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerAdsIT.java
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerXdsIT.java
server/src/test/java/io/envoyproxy/controlplane/server/TestMain.java

cache: Remove need to consumer to specify ads/xds mode in cache

---

api/src/main/proto/envoy/admin/v2/config_dump.proto
api/src/main/proto/envoy/api/v2/auth/cert.proto
api/src/main/proto/envoy/api/v2/cds.proto
api/src/main/proto/envoy/api/v2/core/health_check.proto
api/src/main/proto/envoy/api/v2/lds.proto
api/src/main/proto/envoy/api/v2/route/route.proto
api/src/main/proto/envoy/config/filter/accesslog/v2/accesslog.proto
api/src/main/proto/envoy/config/filter/http/health_check/v2/health_check.proto
api/src/main/proto/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
api/src/main/proto/envoy/config/filter/network/tcp_proxy/v2/tcp_proxy.proto
api/src/main/proto/envoy/config/health_checker/redis/v2/redis.proto
api/src/main/proto/envoy/config/metrics/v2/stats.proto
tools/API_SHAS
tools/update-api.sh

api: Use main envoy repo as source and update API to ca111bc

---

api/pom.xml
pom.xml

deps: Update grpc to 1.12.0

---

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java

By setting the latest response prior to sending the response we
guarantee that the map is updated by the time the corresponding request
arrives. This ensures that the nonce check correctly uses the most
recent response.
Fixes #70

server: set latestResponse before sending response

---

cache/src/main/java/io/envoyproxy/controlplane/cache/Resources.java
cache/src/main/java/io/envoyproxy/controlplane/cache/Snapshot.java
cache/src/main/java/io/envoyproxy/controlplane/cache/TestResources.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SnapshotTest.java
server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
server/src/test/java/io/envoyproxy/controlplane/server/TestMain.java
server/src/test/java/io/envoyproxy/controlplane/server/TestSnapshots.java

Implements SecretDiscoveryService
Fixes #76

cache+server: add support for SDS

---

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java

Fixes #79
Immediately cancel watches when `responseObserver` is cancelled.
Catch cancellation exceptions when responding watches.
Correctly handle cancellations on error.

Handle call cancellation gracefully

---

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java

The problem could be reproduced by following the steps:
- Start a xDS server and the Envoy instance
- Make some change, and push the Cluster, Listener and RouteConfiguration to the Envoy instance.
- Restart the xDS server with empty SnapshotCache, and wait for the Envoy instance connected
- Make some change again, the RouteConfiguration is never been received by the Envoy instance.

Fix bug: the DiscoveryRequest with resource names may never be updated if  xDS server is restarted with empty SnapshotCache

---

OWNERS.md

@snowp - Just realized that I never updated this. Let me know if there's an email you want me to add as well.

docs: add Snow to OWNERS.md

---

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java

Some info logs seem like they should be debug, they are very verbose.

Make some info logs debug

---

cache/src/main/java/io/envoyproxy/controlplane/cache/CacheStatusInfo.java
cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java

Rework locks in cache

---

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java

Refreshed this PR https://github.com/envoyproxy/java-control-plane/pull/93

Send responses in specific order

---

.circleci/config.yml
OWNERS.md
README.md

Signed-off-by: slonka <slonka@users.noreply.github.com>

Fix references to main branch after rename

---

server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerAdsDeltaResourcesIT.java
server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerXdsDeltaResourcesIT.java

Opening this to see if PR requests trigger CI builds

Delta Xds Non Breaking Change

---

pom.xml

latest version of TestContainers

testcontainers 1.15.3

---

.allstar/README.md
.allstar/allstar.yaml
.allstar/binary_artifacts.yaml
.allstar/branch_protection.yaml
.allstar/outside.yaml
.allstar/security.yaml

Add configuration for Allstar.

---

OWNERS.md

Going on parental leave for 5 month, so will not be able to help out with maintenance during that period.

Remove nezdolik from maintainers

---

README.md

There is no mention anywhere in the docs about how to release a new version, so I am documenting it for other maintainers.

Document how to release a new version

---

.circleci/config.yml
pom.xml

Build pipeline for main branch is failing on the gpg signing and javadoc generation.

Bump version for a couple of maven plugins

---

OWNERS.md

I no longer work for Square and I am not currently involved in this
project.
Signed-off-by: Garrett Bourg <bourg.garrett@gmail.com>

Remove baojr from maintainers

---

.github/workflows/scheduled.yml

Temporarily update scheduled workflow to
once per day to aid troubleshooting.

Update schedule to every day

---

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java

verified using `mvn -B install -DskipTests -Dmaven.javadoc.skip=false dependency:go-offline`

remove <p/> tag in java docs

---

api/pom.xml
cache/pom.xml
pom.xml
server/pom.xml
test/pom.xml

This reverts commit 44fff66ce9cf6998c2d9f40b2129c951a7efe548.
I am not sure how/why the commit above got generated, but it's incorrect so I am reverting it.

Revert "release: prepare release v1.0.38"

---

.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/compare-envoy-versions.yml
.github/workflows/scorecard.yml
.github/workflows/update-protobuf.yml
README.md

Setup dependabot for github-actions
Pin actions versions 
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

setup ossf scorecard and codql workflow

---

.github/workflows/compare-envoy-versions.yml
.github/workflows/scheduled.yml
.github/workflows/update-protobuf.yml

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

Improve OSSF score

---

.circleci/config.yml

This is a temp change while I troubleshoot something

troubleshoot gpg issue
