.circleci/config.yml, .circleci/settings.xml, pom.xml
Initial steps towards resolving #5. Maven Central access has been granted for the `io.envoyproxy` group and this PR adds automatic snapshot deployments for all merges to `master`.
=> build: Added snapshot deployment

.circleci/config.yml, api/pom.xml
The protoc plugin is currently configured to always regenerate proto sources, regardless of whether or not there are actual changes. This change configures the plugin to do a staleness check, which avoid regeneration/recompilation when no changes have been made.
The build has also been modified in order to skip javadoc processing during the initial build/test runs.
=> build: Enable protoc plugin staleness check

cache/src/main/java/io/envoyproxy/controlplane/cache/Cache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/NodeGroup.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java
This allows arbitrary types to be used for group keys instead of just
strings. The main motivation behind this is being able to more easily
use structured data for the group identifier instead of having to encode
it as a string.
This simplifies (and even encourages) using grouping to differentiate
envoy instances, e.g. by what app it's deployed alongside.
=> cache: Make the SimpleCache group key generic

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
Instead of using Map<T, Boolean> just use a Set instead. This doesn't
affect behavior at all, it's just more idiomatic Java.
Also some variable name renames just to make the code a little bit clearer to read
=> cache: Refactor Map usage into Set

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
This just adds @GuardedBy to the mutable fields of SimpleCache to
clarify to readers and static analyzers how we ensure that changes made
to these field are made available across threads.
=> cache: Add @GuardedBy to clarifiy how thread safety is achieved

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
This allows passing in the ExecutorService to use instead of always
using the ForkJoinPool. This gives users more control over where the
callback is executed, and also makes it possible to use ExecutorServices
that propagate state to callback threads (e.g. to propagate
trace/logging context).
cc @mpuncel @nicktrav
=> cache: Pass in ExecutorService used for async callbacks in SimpleCache

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java
SimpleCache#watches publishes a non-thread safe member of SimpleCache
without synchronization which means that changes made on other threads
are not guaranteed to be visible.
This change synchronizes access to the watches method and makes a
defensive copy of the underlying data. To simplify this I changed the
data structure from `Map<Map<>>` to `Table`, which let's me use
`ImmutableTable.copyOf` to copy the data more easily.
It also changes usages of #watches() internal to the class to reference
the field directly to avoid the cost of a copy.
This method is just used without synchronization in test right now, so it's probably not a big deal, but I figured it'd make sense to keep the class completely thread safe, even if just to prevent …
=> cache: Make SimpleCache#watches thread safe

cache/src/main/java/io/envoyproxy/controlplane/cache/CacheStatusInfo.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/StatusInfo.java, cache/src/test/java/io/envoyproxy/controlplane/cache/CacheStatusInfoTest.java
Returning the `Node` in the `StatusInfo` doesn't really make sense because it may not be accurate, depending on the `NodeGroup` implementation. It essentially just returns the first `Node` that hashed to a given group.
=> cache: Store node group in StatusInfo instead of node

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
The stream is canceled when the client shuts down without properly
terminating the gRPC stream. This is not really an error (c.f.
https://github.com/grpc/grpc-java/issues/4232) and logging an error here
means a lot of log noise when envoys shut down.
=> server: Don't log an error when stream canceled

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SnapshotCache.java, cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java
This adds a simple getter to SimpleCache that allows retrieving the
current snapshot for a given NodeGroup. Querying the current state of a
group is useful for debugging purposes, test and also for cases where
you might want to inspect the current state before generating a new
snapshot.
=> cache: Add SimpleCache#getSnapshot

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SnapshotCache.java, cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java
Adds a method to SnapshotCache that allows clearing out a Snapshot and
associated metadata. This allows clearing out cache entries that are
known to be no longer needed as a way to keep the size of the cache in
check.
=> cache: add SnapshotCache#clearSnapshot

cache/pom.xml, cache/src/main/java/io/envoyproxy/controlplane/cache/SnapshotResources.java, pom.xml
The lib will still work fine with newer guavas, but dropping the minimum required guava to 20.0 allows us to play nicer with older libs.
=> deps: Downgrade guava to 20.0 and misc minor dep updates

cache/src/main/java/io/envoyproxy/controlplane/cache/ConfigWatcher.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
This makes the DiscoveryServer keep track of the latest acked response,
allowing it to respond to DiscoveryRequests that come in for the
currently acked version but with new resource hints. This reduces the
need for odering the xDs responses: if a CDS response adds a cluster but
we've already sent the EDS response for the current version, Envoy will
be able to retreive the latest version by updating the resource hint and
receiving a new response.
Testing that the DiscoveryService part proved pretty tricky due to all the concurrency
involved in the existing tests, so I'm open to suggestions to how this should be tested.
=> cache/server: keep track of acked responses and respond to new hints

cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java
The CacheStatusInfo#cancel method is already guarded by a mutex, so the
additional locking on the entire SnapshotCache seems to be unnecessary.
Since we're only mutating the CacheStatusInfo and not the SnapshotCache,
the write lock seems like overkill. This should hopefully reduce some of the 
lock contention.
Let me know if i'm missing something obvious that makes this lock necessary.
=> cache: remove cache lock in cancel callback

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
Should any of the callbacks fail, we'll end up not properly canceling
the snapshot watches, causing them to live forever. This PR adds a
finally block to ensure that cancel is always called.
=> server: ensure that watches are canceled during connection close

cache/src/main/java/io/envoyproxy/controlplane/cache/TestResources.java, server/src/test/resources/envoy/ads.config.yaml, server/src/test/resources/envoy/xds.config.yaml
`cluster_names` is deprecated and should no longer be specified. Latest
docker image is failing because of this on master.
[testcontainers-netty-1-2] INFO 🐳 [envoyproxy/envoy-alpine:latest] - STDERR: [2018-07-10 16:40:01.979][18][critical][main] source/server/server.cc:78] error initializing configuration '/tmp/tmp.EjhlgN/envoy.yaml': envoy::api::v2::core::ConfigSource::GRPC must not have a cluster name specified.
=> test: update ConfigSource to no longer use deprecated config

cache/src/main/java/io/envoyproxy/controlplane/cache/Resources.java, cache/src/test/java/io/envoyproxy/controlplane/cache/ResourcesTest.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
In DiscoveryServer we use this method to get the resource names of acked
resources. The type of the passed in object is Any, so `getResourceName(Message)`
responds with `""` since the message doesn't match any of the xds resources. This
adds an overload which will unpack the Any message to the appropriate
Message before determining the resource name.
Added a test that ensures the right resources names are persisted (should have done 
this in the original PR...).
This doesn't seem to always cause issues, but when it does it blasts Envoys with 
updates. We had to roll back our deployment of 0.1.7 because of this.
=> cache: add overload for getResourceName(Any)

cache/pom.xml, cache/src/main/java/io/envoyproxy/controlplane/cache/ConfigWatcher.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/Watch.java, cache/src/main/java/io/envoyproxy/controlplane/cache/WatchCancelledException.java, cache/src/test/java/io/envoyproxy/controlplane/cache/CacheStatusInfoTest.java, cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java, cache/src/test/java/io/envoyproxy/controlplane/cache/WatchTest.java, pom.xml, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
We weren't really doing much with reactor, so it just ended up adding needless complexity. This change drops usage of reactor and migrates to a more traditional response handler system. The main consequence is that we're now executing the handler in the main server thread, but the handler should not block on any long-running calls.
=> cache: Drop reactor, synchronously call watch's response handler

api/pom.xml, pom.xml
This allows java-control-plane to build under 11. The annotation-api
dependency was added to work around https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.m://github.com/grpc/grpc-java/issues/3633
=> build: update jacoco to support java 11

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
This will make it reasonable to provide open source callbacks that can
be used alongside user defined callbacks.
=> server: allow multiple callbacks to be provided

cache/src/main/java/io/envoyproxy/controlplane/cache/Snapshot.java, server/src/main/java/io/envoyproxy/controlplane/server/callback/SnapshotCollectingCallback.java, server/src/test/java/io/envoyproxy/controlplane/server/callback/SnapshotCollectingCallbackTest.java
Adds a callback that watches the streams for requests and stream closes
and cleans up unreferenced snapshots after some time period.
This upstreams the GC mechanism we've been using internally for a few months.
=> server: add a snapshot collecting DiscoveryServerCallbacks

api/pom.xml
See https://github.com/xolstice/protobuf-maven-plugin/issues/5
- Bump protobuf-maven-plugin to 0.6.1
- Use the `useArgumentFile` as it fixes builds on Windows (due to the Windows command line limit)
=> Bump protobuf-maven-plugin version and fix Windows build

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
Errors were being logged when client Envoy closes connection while being shut down/restarted.
This change ensures that errors are not logged when the error code is `CANCELLED`.
Fixes https://github.com/envoyproxy/java-control-plane/issues/83
=> server: ensure errors not logged when client closes connection (#83)

server/src/main/java/io/envoyproxy/controlplane/server/DefaultExecutorGroup.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/main/java/io/envoyproxy/controlplane/server/ExecutorGroup.java
Supersedes #75 
Added concept of `ExecutorGroup` mostly based on netty's `EventExecutorGroup` for distributing `Executor`s to streams in a round robin fashion.
=> cache: respond to watches in parallel v2

cache/pom.xml, cache/src/main/java/io/envoyproxy/controlplane/cache/Resources.java, pom.xml
Checkstyle needs to be updated to resolve a CVE (https://nvd.nist.gov/vuln/detail/CVE-2019-9658). In the process, I also went ahead and brought everything else up to date. Any dependencies that are shared transitively with grpc-java have been set to the version used by grpc-java, even if there is a newer stable version available.
Also, grpc-java no longer transitively depends on protobuf-java-util, so we need to explicitly add it ourselves.
=> deps: bring all dependencies up to date

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/main/java/io/envoyproxy/controlplane/server/serializer/CachedProtoResourcesSerializer.java, server/src/main/java/io/envoyproxy/controlplane/server/serializer/DefaultProtoResourcesSerializer.java, server/src/main/java/io/envoyproxy/controlplane/server/serializer/ProtoResourcesSerializer.java, server/src/test/java/io/envoyproxy/controlplane/server/serializer/CachedProtoResourcesSerializerTest.java, server/src/test/java/io/envoyproxy/controlplane/server/serializer/DefaultProtoResourcesSerializerTest.java
During the java-control-plane performance debugging I've noticed that the proto with resources is built on every response which is then stored in the `lastResponse`. This is huge pressure on GC when you run java-control-plane with many Envoys that receives the same set of resources (for example: edge envoys).
That is why I introduced Guava cache with `weakValues()`. So as long as any `DiscoveryRequestStreamObserver#lastResponse` will keep the value, it will be served from the cache. Otherwise it will be wiped with the next GC.
I run the test when connected to 300 envoys on ADS on single instance of our control plane. Every envoy gets all the state of our discovery which is ~700 clusters and couple of thousands endpoints. Here is the result
Before this change is the instance with green …
=> server: Cache serialized protos

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServerCallbacks.java, server/src/main/java/io/envoyproxy/controlplane/server/exception/RequestException.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java
This PR adds possibility to validate DiscoveryRequest and return custom error response to the client.
Envoy will show our custom status code and description in logs with `warning` level:
```
gRPC config stream closed: 3, custom validation error message
```
instead of generic:
```
gRPC config stream closed: 2, 
```
Fixes #104
=> server: return custom error response for invalid DiscoveryRequest

.circleci/config.yml
Similar to the protoc-gen-validate build, use the shared envoy-bot user rather than our envoy-java-control-plane-bot user.
=> build: deprecate envoy-java-control-plane-bot

OWNERS.md
As discussed over the envoy-maintainers thread, please allow adding myself, @jakubdyszkiewicz and @slonka to the OWNERS.md file.
=> docs: add Allegro team members to OWNERS.md

server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java
Synchronize access to `responseObserver` to prevent races:
```
java.lang.IllegalStateException: call already closed
at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:172)
at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:142)
at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:341)
at io.envoyproxy.controlplane.server.DiscoveryRequestStreamObserver.send(DiscoveryRequestStreamObserver.java:133)
at io.envoyproxy.controlplane.server.DiscoveryRequestStreamObserver.lambda$processRequest$3(DiscoveryRequestStreamObserver.java:109)
at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
at …
```
=> Synchronize access to responseObserver

cache/src/main/java/io/envoyproxy/controlplane/cache/Watch.java, server/src/main/java/io/envoyproxy/controlplane/server/AdsDiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/main/java/io/envoyproxy/controlplane/server/XdsDiscoveryRequestStreamObserver.java
The objective of this PR is to reduce the complexity and overhead when not operating in ADS mode.
When working with separate XDS streams the StreamObserver logic can be much simpler and it does not need to store maps, thus reducing the memory overhead.
This also includes a change in `Watch` and `StreamObserver` to use `Atomic*FieldUpdaters` instead of `Atomic*` which reduces the memory overhead per instance.
I realize this introduces a bit of indirection and probably code complexity, but this should be a win when not operating in ADS mode and having thousands of streams.
=> server: Refactor stream observer

OWNERS.md
I'm changing my e-mail to private one, because soon I'll be leaving Allegro.
If possible, I'd like to stay as a maintainer of the project. I will still continue to work on Envoy-based Service Mesh, though more on the Go side. Knowing better the go-control-plane, I might bring some ideas to the java-control-plane.
=> Owner e-mail change

.circleci/config.yml, .circleci/settings-snapshots.xml
Add ability to manually trigger publishing of snapshot artifacts from a branch.
Separate maven settings file is provided to prevent from publishing a release by mistake.
=> CircleCI: manual snapshot deployment from branch

server/pom.xml, server/src/main/java/io/envoyproxy/controlplane/server/AdsDiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/LatestDiscoveryResponse.java, server/src/main/java/io/envoyproxy/controlplane/server/XdsDiscoveryRequestStreamObserver.java
Some of our services are watching changes of all services. Because of this `latestResponse` might be really heavy and put pressure on GC because of number of changes. In our case each `AdsDiscoveryRequestStreamObserver` weight around 20MB. Let's say we have 20 services connected to one instance of control plane. It gives 400MB allocated for each change.
Because we don't use whole data from Response I've added change which story only used data in object: nonce and resourceNames. Thanks to this change our GC pressure dropped:
=> Dont save whole response just data needed during another request

cache/src/main/java/io/envoyproxy/controlplane/cache/ConfigWatcher.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/TestResources.java, cache/src/test/java/io/envoyproxy/controlplane/cache/SimpleCacheTest.java, server/src/main/java/io/envoyproxy/controlplane/server/AdsDiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryRequestStreamObserver.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerAdsIT.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerAdsWarmingClusterIT.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerTest.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerXdsIT.java, server/src/test/java/io/envoyproxy/controlplane/server/EchoContainer.java, server/src/test/java/io/envoyproxy/controlplane/server/TestSnapshots.java
On our development environment we found that if snapshot already exists and new Envoy connects to EC it might respond immediately in `createWatch` method. Method `setSnapshot` can ensure that EDS will be sent after CDS but here we can't be sure that. I've tested this with ADS mode and also made changes for this mode.
This is how it looks like:
1. Envoy connects to control-plane
2. Snapshot already exists in control-plane <- other instance share same group
3. Control-plane respond with CDS in createWatch method
4. There is snapshot update which change CDS and EDS versions
5. Envoy sends EDS request
6. Control-plane respond with EDS in createWatch method
7. Envoy resume CDS and EDS requests. 
8. Envoy sends request CDS
9. Control plane respond with CDS in createWatch method
10. Envoy sends …
=> Send EDS response after CDS even if EDS hasn't change

cache/src/main/java/io/envoyproxy/controlplane/cache/GroupCacheStatusInfo.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, server/src/test/java/io/envoyproxy/controlplane/server/DiscoveryServerAdsWarmingClusterIT.java, server/src/test/java/io/envoyproxy/controlplane/server/EnvoyContainer.java
Since PR #128 was merged we noticed a considerable increase in the time it takes for our control plane to do a `setSnapshot` operation, we have 1.5M watches per control plane machine, and that change makes the control plane have to iterate over those 1.5M watches up to 5 times.
The change is pretty straight forward and should have no issues, the only thing that's weird is that `SnapshotCache` provides a method for getting a `StatusInfo` and now we have a map, I found two solutions for this, either we break API compatibility and make `statusInfo(T group)` receive the desired typeUrl or we provide a wrapper `StatusInfo` clas which wrapps a collection of `CacheStatusInfo` and exposes the same API. I took the latter.
=> Store cache status info in a map by type url

server/src/test/java/io/envoyproxy/controlplane/server/V2DiscoveryServerAdsWarmingClusterIT.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerAdsWarmingClusterIT.java
pinging @lukidzi as the original author of the test. The original tests succeed only in [1 per ~10 tests](https://app.circleci.com/pipelines/github/envoyproxy/java-control-plane?branch=master). I think this is because we use `envoy:latests` in our docker image setup and hitting this edge case became less probable over time. The change I suggest here [still hits this statement](https://github.com/envoyproxy/java-control-plane/pull/131/files#diff-365acc783365f5bf5c56440076a23e9dR134) as shown by coverage report. attached below:
[coverage reports.zip](https://github.com/envoyproxy/java-control-plane/files/5263492/coverage.reports.zip)
the ordering check is not hit because I removed the "empty" respondInOrder (now it *does* respond in order so I'm guessing that's why the ordering check is not …
=> Fix flapping warming cluster integration tests

pom.xml
Signed-off-by: slonka <slonka@users.noreply.github.com>
=> Bump nexus release plugin timeout to 20 minutes

pom.xml
```
fixes:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadocs) on project api: Execution attach-javadocs of goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar failed: Cannot invoke "org.apache.commons.lang3.JavaVersion.atLeast(org.apache.commons.lang3.JavaVersion)" because "org.apache.commons.lang3.SystemUtils.JAVA_SPECIFICATION_VERSION_AS_ENUM" is null -> 
on java8+
additionally bumped up jacoco plugin version.
```
=> fixes javadoc plugin issue

OWNERS.md
As much as I'd love to keep a status of a maintainer of `java-control-plane`, I simply do not have time at this moment to contribute.
See you in the other envoy related projects!
=> docs: remove jakubdyszkiewicz from OWNERS.md

.circleci/config.yml
CircleCI has a default "no output" timeout of 10 minutes, after which a build will fail (see https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-hit-timeout-limit). This causes the build pipeline to - at times - fail during the mvn build step, as there can be certain tasks in maven that don't output anything for longer than this timeout.
So I am doubling the timeout period to - hopefully - make the build pipeline less prone to flaky failures.
@onemanbucket Can you please take a look?
=> Bump default "no output" timeout of 10 minutes for build step

cache/src/main/java/io/envoyproxy/controlplane/cache/v2/SimpleCache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/v2/Snapshot.java, server/src/main/java/io/envoyproxy/controlplane/server/V2DiscoveryServer.java
Deprecate V2 and mark for removal, since Envoy has now removed support for v2 xDS API.
=> deprecate v2

.github/workflows/update-protobuf.yml, tools/update-api.sh, tools/update-sha.sh
I had to update a couple of things to get the github action that upgrades the Envoy API to run successfully. 
I have tested it in my fork for Envoy v1.21.0, so the next step would be to configure it to run automatically whenever a new Envoy version is released. 
Here is the PR that was created through the github action -> https://github.com/rulex123/java-control-plane/pulls
@onemanbucket can you take a look when you get a chance?
=> Fix gitHub action to upgrade envoy protos

.circleci/config.yml
As per instructions here
https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/?mkt_tok=NDg1LVpNSC02MjYAAAGCndauQAv9-BZZXCTbKMjSUMJIhX8nGsCwm9FblTbEN75h56uBn3TgzeOFj_a_8CJbpZGZKf7gFRp3Qj2IFgEY3SQmQzG96brfnrsLBJCTXefs#changes
The Ubuntu 14.04 image is being deprecated at the end of May 2022, so this patch updates to the new suggested image for the CircleCI jobs.
=> Migrating from Ubuntu 14.04 to Ubuntu 20.04 for Circle CI jobs

.circleci/config.yml
The main build pipeline is failing on the gpg import command
(as far as I can gather at least) since the switch to the latest
ubuntu image for CircleCI. I did some troubleshooting rerunning
the failed job with SSH enabled, and it appears that the gpg 
command is running in interactive mode (i.e. asks for passphrase 
input)
=> Try and fix main build pipelines

server/src/test/java/io/envoyproxy/controlplane/server/EnvoyContainer.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerAdsIT.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerAdsWarmingClusterIT.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerXdsIT.java
Remove --bootstrap-version from args in envoy test container,
since this has been removed from the availble command line args.
=> Remove --bootstrap-version when starting up Envoy test container

server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerAdsWarmingClusterIT.java
A connect timeout value of 0 will cause Envoy to return a proto 
validation error. The connect timeout value for this specific test 
is picked at random (with an upper bound only), so to fix we also
set a lower bound.
=> Fix flakiness in integration test

.github/workflows/manual-update-protobuf.yml
Temporarily introduce a github action that can be
run manually via Github web UI and that updates the
Envoy API to a given version. This is needed to update
to v1.22.0.
=> Temp github action

server/src/main/java/io/envoyproxy/controlplane/server/AdsDiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DeltaDiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServerCallbacks.java, server/src/main/java/io/envoyproxy/controlplane/server/V3DiscoveryServer.java, server/src/main/java/io/envoyproxy/controlplane/server/exception/RequestException.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerAdsStreamOpenExceptionIT.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerTest.java, server/src/test/java/io/envoyproxy/controlplane/server/V3OnlyDiscoveryServerCallbacks.java
This PR introduces throwing a checked exception from stream callbacks, and catching them to trigger clean up tasks such as calling onStreamClose(WithError)
This follows a similar pattern to the go-control-plane where certain callbacks can return errors https://github.com/envoyproxy/go-control-plane/blob/bf9fc1db9d0fefb8df1291fc4638b0f2d7f39a7e/pkg/server/v3/server.go#L70-L81
And a defer statement calls OnStreamClosed
https://github.com/envoyproxy/go-control-plane/blob/bf9fc1db9d0fefb8df1291fc4638b0f2d7f39a7e/pkg/server/sotw/v3/server.go#L93-L98
Signed-off-by: Shulin Jia <shulin@squareup.com>
=> server: allow throwing checked exception from stream callbacks

tools/update-sha.sh
Update tooling that keeps Envoy protobuf files in sync
to find and replace the current release tag in the docker image
used for testing and replace it with the new release.
=> Update tooling to replace release tag in EnvoyContainer.java

cache/src/main/java/io/envoyproxy/controlplane/cache/ConfigWatcher.java, cache/src/main/java/io/envoyproxy/controlplane/cache/SimpleCache.java, cache/src/main/java/io/envoyproxy/controlplane/cache/TestResources.java, cache/src/main/java/io/envoyproxy/controlplane/cache/Watch.java, cache/src/test/java/io/envoyproxy/controlplane/cache/CacheStatusInfoTest.java, cache/src/test/java/io/envoyproxy/controlplane/cache/WatchTest.java, cache/src/test/java/io/envoyproxy/controlplane/cache/v3/SimpleCacheTest.java, server/src/main/java/io/envoyproxy/controlplane/server/DefaultStartupConfigs.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryRequestStreamObserver.java, server/src/main/java/io/envoyproxy/controlplane/server/DiscoveryServer.java, server/src/main/java/io/envoyproxy/controlplane/server/StartupConfigs.java, server/src/main/java/io/envoyproxy/controlplane/server/V3DiscoveryServer.java, server/src/test/java/io/envoyproxy/controlplane/server/EchoContainer.java, server/src/test/java/io/envoyproxy/controlplane/server/EnvoyContainer.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerAdsAllowDefaultEmptyEdsIT.java, server/src/test/java/io/envoyproxy/controlplane/server/V3DiscoveryServerTest.java, server/src/test/java/io/envoyproxy/controlplane/server/V3OnlyDiscoveryServerCallbacks.java
race condition may happen in ADS mode, cluster can be removed from envoy-control when envoy asks for EDS response. 
Since the cluster is not in the snapshot, envoy-control will not respond envoy with EDS response and these clusters will be in warming status forever. 
So we add allowIncompleteEdsUpdate server startup config to allow ADS server to respond incomplete EDS response.
=> TRAFFIC-4937 add server startup config to allow incomplete EDS response

.github/workflows/scheduled.yml, .github/workflows/update-protobuf.yml
After last week's changes to github workflows, the jobs scheduled to run
every day that check the latest available envoy version and update protobuf
files (if needed) are failing due incorrect permissions. This patch attempts
to fix this issue.
=> Fix failure for update_protobuf workflow

tools/update-api.sh, tools/update-sha.sh
Currently broken because of an update in the repository_locations.bzl file for Envoy v1.29.0.
=> Fix update-protobuf workflow

.github/workflows/update-protobuf.yml
The `update-protobuf` workflow is still failing due to lack of permissions 
on pushing a branch. We need to set `contents: write` permission according to the documentation here
https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#workflow-permissions
=> Fix update-protobuf workflow (we are getting closer =))

.github/workflows/scheduled.yml
There are still failures in the automation that keeps the proto files
sync'd with envoy releases due insufficient permissions for scope
`content`
=> update permissions in caller workflow

.circleci/config.yml
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
=> Replace image as it has reached EOL

tools/update-api.sh, tools/update-sha.sh
Currently the automation that keeps API protos in sync with Envoy releases is broken due to this missing dependency
=> Add CEL Common Expression Language to scripts that grap protos

.circleci/settings-snapshots.xml, .circleci/settings.xml
Token was generated as per instructions ->https://central.sonatype.org/publish/generate-token/
New env variables were added to the project settings in CircleCI so that they can be used by builds.
=> switch to user token to authenticate against Sonatype server
